### ISSUE TITLE
constructor failed with class not exists error

### ISSUE THREAD

**Issue by libbit702** [intekhabrizvi/codeigniter-mongodb-library#1]
Hi, my development is installed with lnmp all-in-one package:
PHP Version 7.2.9
MongoDB extension version | 1.5.2
CodeIgniter:3.1.7

and after I implemented the CIMongo library in autoload config, then the page shows error:
"The MongoDB PECL extension has not been installed or enabled"

I did check my php-fpm environment with phpinfo and it showed mongodb extension enabled. 
I checked the source and found this error was raised by 
`
if ( ! class_exists('MongoDB'))
		{
			show_error("The MongoDB PECL extension has not been installed or enabled", 500);
		}
`
I checked another ci mongo lib on github, and it used another way to check if the library exist with a full namespace
[https://github.com/verkhoumov/codeigniter-mongodb-library/blob/master/application/libraries/Mongo_db.php#L203](url)

Is there anything wrong with my implementation?

**Comment by intekhabrizvi** [comment]
Thanks for pointing out the issue. I updated the codes in commit 360b727 it should work without any problem.
