### ISSUE TITLE
Distinct Query don't work!!

### ISSUE THREAD

**Issue by mtavares2** [intekhabrizvi/codeigniter-mongodb-library#11]
Hi,
I try made $this->mongo_db->distinct("") from library bu get errors like this:

A PHP Error was encountered
Severity: Notice

Message: Undefined property: MongoDB\Driver\Manager::$match

Filename: libraries/Mongo_db.php

Line Number: 1336

Backtrace:

File: C:\etc\www\folder\application\libraries\Mongo_db.php
Line: 1336
Function: _error_handler

File: C:\etc\www\folder\application\controllers\inicio.php
Line: 21
Function: distinct

File: C:\etc\www\folder\index.php
Line: 315
Function: require_once

An uncaught Exception was encountered
Type: Error

Message: Call to a member function distinct() on null

Filename: C:\etc\www\folder\application\libraries\Mongo_db.php

Line Number: 1336

Backtrace:

File: C:\etc\www\folder\application\controllers\inicio.php
Line: 21
Function: distinct

File: C:\etc\www\folder\index.php
Line: 315
Function: require_once

I need some help urgent, please!!!

**Comment by setdjod** [comment]
Same problem

**Comment by Xeramos** [comment]
I have Fix this Bug, i send a pull request the next days

**Comment by intekhabrizvi** [comment]
@mtavares2 @setdjod distinct function accept 2 compulsory params 1st is the name of collection and the 2nd is the field name you wan "distinct" to be perform, i can see that you are skip both param.

See the documentation of function 
`@usage: $this->mongo_db->distinct('collection', 'field');`

@Xeramos could you pls point me to the error.
