### ISSUE TITLE
How to select nested object field or use them in the where clause?

### ISSUE THREAD

**Issue by ganmahmud** [intekhabrizvi/codeigniter-mongodb-library#18]
For an example, here's my parent object - project :

`
project = {
tasks : [
{
task_id: "123",
task_name: "Some task",
}
]
}`

`$this->mongo_db->select(array("task"))->get("projects")` - this will fetch the whole tasks object. 

But I want to select task_name of each tasks.  I tried few things but it didn't work.

`select(array("task.task_name"))` does not work. I also tried it in the where clause,  
`$this->mongo_db->where('task.task_name' , "Some task");` , but it also didn't work. Any kind help would be highly appreciated. Thanks.

**Comment by Xeramos** [comment]
Hello ganmahmud,

I have create the same collection and test it
This work fine
`$result = $this->mongo_db->where('task.task_name', "Some task")
	  									 ->select(array('task.task_id', 'task.task_name'))
										 ->get('project');
	   echo nl2br(print_r($result, true));`
Result:
`Array
(
[0] => Array
(
[task] => stdClass Object
(
[task_id] => 123
[task_name] => Some task
)
[_id] => stdClass Object
(
[$id] => 5d739aa920ed402e78a15f3e
)
)
)`

**Comment by intekhabrizvi** [comment]
The suggestion given by @Xeramos is correct.

**Comment by ganmahmud** [comment]
@Xeramos @intekhabrizvi thanks. 
Do you have any idea how can I update a  specific object item from a nested array inside a document.
For an example: 
I have a collection named - `projects`. For each of its document I have a field named `milestones` which is an array of objects -
```
{
  project_id: 123,
  "milestones": [
         {
            'milestone_id': '001'
            'milestone_title': 'Milestone title 1',
         },
         {
             'milestone_id': '002'
             'milestone_title': 'Milestone title 2',
         }
   ]
}
```
How can I update the milestone array item title where milestone_id == '002' ?
