### ISSUE TITLE
 MongoDB\Driver\Exception\InvalidArgumentException

### ISSUE THREAD

**Issue by maxsteel753** [intekhabrizvi/codeigniter-mongodb-library#20]
Type: MongoDB\Driver\Exception\InvalidArgumentException

Message: MongoDB\BSON\ObjectId::__construct() expects parameter 1 to be string, object given

[_id] => stdClass Object
        (
            [$id] => 5d78dd3d953b9c43aa194cb9
        )
print_r((string) new MongoDB\BSON\ObjectId($campaignData['_id']));

**Comment by intekhabrizvi** [comment]
You are accessing the PHP function directly and the error you are seeing is from PHP not from this library [pls check this example](https://www.php.net/manual/en/class.mongodb-bson-objectid.php#122051) for proper use of the PHP function.
