### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by ajay-jain** [intekhabrizvi/codeigniter-mongodb-library#21]
{
	"status": false,
	"error": {
		"classname": "MongoDB\\Driver\\Exception\\AuthenticationException",
		"message": "Authentication failed."
	}
}

I have entered correct username and password still it gives me that error in below method.  

$cursor = $this->db->executeQuery($this->database.".".$collection, $query, $read_preference);

**Comment by intekhabrizvi** [comment]
Please check your connection to MongoDB server.
Passing correct user id and password is not sufficient for confirmed connection.
There is nothing wrong with the library.

**Comment by ajay-jain** [comment]
I did few changes in connect function 

 **$dns = "mongodb://{$this->username}:{$this->password}@{$this->hostname}:{$this->port}";**

I have passed username and password in connection. Now it is working fine. 

**Final Code**

       $dns = "mongodb://{$this->hostname}:{$this->port}/{$this->database}";
       if (isset($this->config[$this->activate]['no_auth']) && $this->config[$this->activate]['no_auth']) {
                $options = array();
       } else {
      $dns = "mongodb://{$this->username}:{$this->password}@{$this->hostname}:{$this->port}";
                $options = array('username' => $this->username, 'password' => $this->password);
       }
