### ISSUE TITLE
'The 'cursor' option is required' error while using the aggregation

### ISSUE THREAD

**Issue by ganmahmud** [intekhabrizvi/codeigniter-mongodb-library#25]
I have this following data in a collection named 'projects' : 
```
{
name: 'Some name 1',
category: 'Category A'
}
{
name: 'Some name 1',
category: 'Category A'
}
{
name: 'Some name 1',
category: 'Category B'
}
{
name: 'Some name 1',
category: 'Category B'
}
```
I am trying to use aggregate to to group the data and put a limit (let's assume limit = 1 here) for each group so that the result would like this - 
```
{
name: 'Some name 1',
category: 'Category A'
}
{
name: 'Some name 1',
category: 'Category B'
}
```
Here's how I am trying - 
```
 $ops = [
    ['$group' => ['_id' => 'program']],
    ['$limit' => 1]
 ];
 $this->mongo_db->aggregate('projects', $ops);
```
But I am getting the following error -
```
Type: MongoDB\Driver\Exception\CommandException
Message: The 'cursor' option is required, except for aggregate with the explain argument
```
Am I writing the aggregation syntax in proper way. I am still learning. A sample code for this type of scenario would be really helpful for me. Thanks. 
note: I am using mongo 4.0.10

**Comment by ganmahmud** [comment]
Update:

Found a solution. I just had to mention the cursor as the third command parameter in the aggregate method.

**Comment by Xeramos** [comment]
Can you Explain how you do this ? I have the same problem

**Comment by ganmahmud** [comment]
@Xeramos In the aggregate method, before returning -
`$command = array('aggregate'=>$collection, 'pipeline'=>$operation, 'cursor' => new stdClass);`
