### ISSUE TITLE
Update method is not clearing after execution

### ISSUE THREAD

**Issue by libbit702** [intekhabrizvi/codeigniter-mongodb-library#3]
Hi, I ran into a strange issue when I try to update one single document each time in a loop function, 
I found the update data is getting bigger and bigger as the loop went on, and every new update seemed to have old data added in the previous loop.

I checked the soucrce code and found that _clear function is not called either in update or update_all in the new lib, while I saw that function called in [legacy version of this library](https://github.com/intekhabrizvi/Codeigniter-mongo-library/blob/master/application/libraries/Mongo_db.php#L1249)

Could this missing function be the reason?

**Comment by intekhabrizvi** [comment]
Thanks for pointing out the issue, commit 800f967 could fix your reported problem.
Please let me know if its fail to work.
