### ISSUE TITLE
 $this->mongo_db->count('foo'); very slow.

### ISSUE THREAD

**Issue by zairoo** [intekhabrizvi/codeigniter-mongodb-library#34]
@usage : $this->mongo_db->count('foo');

count are very slow when there are 100,000 data.

**Comment by intekhabrizvi** [comment]
The slow or fast response is completely depends on server or on your query. In your case your server is taking time to count all the documents in particular collection hence library is waiting until the job is finish.

**Comment by zairoo** [comment]
this method performs better.

`            $query = new MongoDB\Driver\Query($filter, $options);
            $command = new MongoDB\Driver\Command(
                array(
                    "count" => $collection,
                    "query" => $query,
                )
            );
            $count = $this->db->executeCommand($this->database,$command)->toArray()[0]->n;`

**Comment by zairoo** [comment]
it is not actually a server problem. 
when there are many data records, executeQuery is not a good method. 
hope to improve.
