### ISSUE TITLE
Mispelling $commond => $command

### ISSUE THREAD

**Issue by bboy-space** [intekhabrizvi/codeigniter-mongodb-library#5]
https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1830

**Comment by bboy-space** [comment]
Same here : 
https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1860

https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1882

https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1917

https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1938

**Comment by najdanovicivan** [comment]
Ref #17

**Comment by intekhabrizvi** [comment]
Pull request to fix this issue is merged, thanks all for informing.
