### ISSUE TITLE
 MongoDB\Driver\Exception\InvalidArgumentException

### ISSUE THREAD

**Issue by maxsteel753** [intekhabrizvi/codeigniter-mongodb-library#6]
MongoDB\Driver\ReadPreference::__construct() expects parameter 1 to be integer, string given
Line Number: 841

Backtrace:

File: /usr/share/nginx/html/travelweb/application/libraries/Mongo_db.php
Line: 841
Function: __construct

**Comment by najdanovicivan** [comment]
Related to #15
