### ISSUE TITLE
update multiple doc option invalid

### ISSUE THREAD

**Issue by libbit702** [intekhabrizvi/codeigniter-mongodb-library#8]
https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1442

http://php.net/manual/zh/mongocollection.update.php
old driver used 'multiple' while MongoDB\Driver\BulkWrite use 'multi' 
http://php.net/manual/zh/mongodb-driver-bulkwrite.update.php

**Comment by intekhabrizvi** [comment]
Thanks, Issue fixed in commit e8d4007
