### ISSUE TITLE
Delete Params Invalid compared to official document

### ISSUE THREAD

**Issue by libbit702** [intekhabrizvi/codeigniter-mongodb-library#9]
https://github.com/intekhabrizvi/codeigniter-mongodb-library/blob/22f7722c0d89ec82b81f45bf745e769e2a855841/application/libraries/Mongo_db.php#L1504

PHP official doc provided an example , and it only has two params while the code above used three, same thing happened on delete_all function, pls check it out
`<?php

$bulk = new MongoDB\Driver\BulkWrite;
$bulk->delete(['x' => 1], ['limit' => 1]);
$bulk->delete(['x' => 2], ['limit' => 0]);

$manager = new MongoDB\Driver\Manager('mongodb://localhost:27017');
$result = $manager->executeBulkWrite('db.collection', $bulk);

?>`

**Comment by intekhabrizvi** [comment]
Thanks for pointing it, its fixed in commit 8b037ad
